import Head from "next/head";
import BrandSlider from "../components/home_components/Hero/Hero"

export default function Home() {
  return (
    <>
      <Head>
        <title>Orion Ux labs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="container-fluid p-0 m-0">
        <BrandSlider/>
        </div>
      </main>
    </>
  );
}
